### ISSUE TITLE
[EP] Change type of A97 to `string`

### ISSUE THREAD

**Issue by stiebitzhofer** [thematerials-network/EN10168-schemas#33]
## Describe the problem
A typical order number including its position in SAP looks like

> 20502841 000020

with 
* 20502841 as the order number
* 000020 as the position number. 

In the current design, the order position number (A97) is of type number so the result would be `20`.

## Specify the details
The solution is to change 

```JSON
        "A97": {
          "description": "A custom field for the position number in the order",
          "type": "number"
        },
```

to 

```JSON
        "A97": {
          "description": "A custom field for the position number in the order",
          "type": "string"
        },
```

## Explain the benefits
Users will be able to read SAP position numbers according to their expectations.

**Comment by stiebitzhofer** [comment]
@mzinnoecker Can you please review and comment?

**Comment by mzinnoecker** [comment]
hey @stiebitzhofer,
totally agree.
From a functional point of view the leading zeros are required.
From a rendering point of view, i - as a enduser - may not expect the leading zeros in a pdf output, right? (but maybe that's a different topic)
The point here definately makes sense. What can be discussed is a length restriction, as position numbers in SAP are usually not greater than length 6. (but a restriction is not needed from my perspective - just wanted to note)
